[tool.poetry]
name = "celltracking"
version = "0.1.0"
description = ""
authors = ["Heather Deter, W.R. Jackson"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.2"
scipy = "^1.5.2"
imageio = "^2.9.0"
opencv-python = "^4.4.0"
ipython = "^7.18.1"
matplotlib = "^3.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
