[tool.poetry]
name = "Beholder"
version = "0.1.0"
description = ""
authors = ["W.R. Jackson"]

[tool.poetry.dependencies]
python = "^3.8"
tensorflow = "^2.3.1"
opencv-python = "^4.4.0"
click = "^7.1.2"
imageio = "^2.9.0"
tqdm = "^4.50.2"
pims = "^0.5"
nd2reader = "^3.2.3"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
